### ISSUE TITLE
Support de macOS Safari

### ISSUE THREAD

**Issue by mackoj** [Sykless/pokemon-showdown-fr#1]
Bonjour,

Est ce que vous pouvez supporter [Safari](https://developer.apple.com/documentation/safariservices/safari_web_extensions/creating_a_safari_web_extension) ? 

Merci d'avance

Je l'aurai bien fait moi même cependant je n'ai l'impression d'avoir le droit de le faire.

> Droits d'auteurs
> 
> Merci de noter que même si le code est publiquement accessible, il est protégé par les droits d'auteurs, l'exclusive Copyright et les conditions d'utilisations de Github, qui empêchent toute réappropriation et redistribution du code.

Cordialement,

**Comment by Sykless** [comment]
Hello !
Pour poster une extension sur Safari, il faut payer une licence Apple Developer Program qui coûte 99$ par an, donc le projet ne sera pas porté sur Safari !

Si tu le souhaites et a les compétences, tu peux adapter le code pour ton utilisation personnelle, tant que tu ne redistribues pas ton code. :')
Bon courage !

**Comment by mackoj** [comment]
Merci @Sykless,

Il est possible de distribuer une version non signé il faut juste faire [quelques manip de plus(Configure Safari in macOS to run unsigned extensions)](https://developer.apple.com/documentation/safariservices/safari_web_extensions/running_your_safari_web_extension) pour le faire fonctionner... C'est ce que j'ai fait moi si tu veux je peux te l'exporter.

Et la version que j'ai fonctionne sur iOS / macOS donc sur iPad.

En tout cas merci 🙏 pour avoir fait le boulot de trad pour Showdown.

![Capture d’écran 2022-11-16 à 11 20 17](https://user-images.githubusercontent.com/661647/202154900-d5943a0e-9ae8-459d-948f-3ec9b2511ecf.png)
![Capture d’écran 2022-11-16 à 11 20 07](https://user-images.githubusercontent.com/661647/202154907-4161e03a-41e3-44e7-8425-2b970fe56501.png)
![Capture d’écran 2022-11-16 à 11 19 57](https://user-images.githubusercontent.com/661647/202154910-f8e3fe8a-7357-4cc3-80b1-23a34f2e40ef.png)
