### ISSUE TITLE
Terracristal traduction mauvaise

### ISSUE THREAD

**Issue by BastienBoymond** [Sykless/pokemon-showdown-fr#2]
La traduction sur les terrracristals n'est pas bonne
![image](https://user-images.githubusercontent.com/71839723/204063103-91da2766-dcff-42ff-9120-687d39144488.png)

**Comment by Sykless** [comment]
Yes c'est normal, la version 1.2 ne prenait en compte que les noms des Pokémon/attaques/talents/objets, l'interface viendra dans la prochaine mise à jour !

Pour la suite si tu as une suggestion ou une notification d'erreur de traduction, n'hésite pas à rejoindre le [Discord Pokémon Showdown FR](https://discord.gg/hRacUWR2wc) !
